-- This creation script should work in most flavors of SQL.
-- Logically, canonical_name is a primary key although no
-- constraint or index is included.
create table nicknames (
canonical_name varchar(255),
  nickname_1 varchar(255),
  nickname_2 varchar(255),
  nickname_3 varchar(255),
  nickname_4 varchar(255),
  nickname_5 varchar(255),
  nickname_6 varchar(255),
  nickname_7 varchar(255),
  nickname_8 varchar(255),
  nickname_9 varchar(255),
  nickname_10 varchar(255),
  nickname_11 varchar(255),
  nickname_12 varchar(255),
  nickname_13 varchar(255),
  nickname_14 varchar(255),
  nickname_15 varchar(255)
);
-- These insert statements are verbose, but they could not be simpler to use.
insert into nicknames values ('aaron', 'erin', 'ron', 'ronnie');
insert into nicknames values ('abbigail', 'abbe', 'abbey', 'abbi', 'abbie', 'abby', 'gail', 'nabby');
insert into nicknames values ('abbigale', 'abbe', 'abbey', 'abbi', 'abbie', 'abby', 'gail', 'nabby');
insert into nicknames values ('abednego', 'bedney');
insert into nicknames values ('abel', 'ab', 'abe', 'eb', 'ebbie');
insert into nicknames values ('abiel', 'ab');
insert into nicknames values ('abigail', 'abbe', 'abbey', 'abbi', 'abbie', 'abby', 'gail', 'nabby');
insert into nicknames values ('abigale', 'abbe', 'abbey', 'abbi', 'abbie', 'abby', 'gail', 'nabby');
insert into nicknames values ('abijah', 'ab', 'bige');
insert into nicknames values ('abner', 'ab');
insert into nicknames values ('abraham', 'ab', 'abe');
insert into nicknames values ('abram', 'ab', 'abe');
insert into nicknames values ('absalom', 'ab', 'abbie', 'app');
insert into nicknames values ('ada', 'addy', 'adie');
insert into nicknames values ('adaline', 'ada', 'addy', 'adie', 'delia', 'dell', 'lena');
insert into nicknames values ('addison', 'addie', 'addy');
insert into nicknames values ('adela', 'adie', 'della');
insert into nicknames values ('adelaide', 'addy', 'adele', 'adie', 'dell', 'della', 'heidi');
insert into nicknames values ('adelbert', 'albert', 'bert', 'del', 'delbert');
insert into nicknames values ('adele', 'addy', 'dell');
insert into nicknames values ('adeline', 'ada', 'addy', 'delia', 'dell', 'lena');
insert into nicknames values ('adelphia', 'addy', 'adele', 'dell', 'delphia', 'philly');
insert into nicknames values ('adena', 'adina', 'deena', 'dena', 'dina');
insert into nicknames values ('adolphus', 'ado', 'adolph', 'dolph');
insert into nicknames values ('adrian', 'rian');
insert into nicknames values ('adriane', 'riane');
insert into nicknames values ('adrienne', 'addie', 'enne', 'rienne');
insert into nicknames values ('agatha', 'aga', 'aggy');
insert into nicknames values ('agnes', 'aggy', 'inez', 'nessa');
insert into nicknames values ('aileen', 'allie', 'lena');
insert into nicknames values ('alan', 'al');
insert into nicknames values ('alanson', 'al', 'lanson');
insert into nicknames values ('alastair', 'al');
insert into nicknames values ('alazama', 'ali');
insert into nicknames values ('albert', 'al', 'bert');
insert into nicknames values ('alberta', 'allie', 'bert', 'bertie');
insert into nicknames values ('aldo', 'al');
insert into nicknames values ('aldrich', 'rich', 'riche', 'richie');
insert into nicknames values ('aleksandr', 'alek', 'alex');
insert into nicknames values ('aleva', 'leve', 'levy');
insert into nicknames values ('alex', 'al');
insert into nicknames values ('alexander', 'al', 'alec', 'alex', 'sandy');
insert into nicknames values ('alexandra', 'alex', 'alla', 'sandra', 'sandy');
insert into nicknames values ('alexandria', 'alex', 'alexander', 'alla', 'drina', 'sandra');
insert into nicknames values ('alexis', 'alex', 'lexi');
insert into nicknames values ('alfonse', 'al');
insert into nicknames values ('alfred', 'al', 'fred', 'freddy');
insert into nicknames values ('alfreda', 'alfy', 'freda', 'freddy', 'frieda');
insert into nicknames values ('algernon', 'algy');
insert into nicknames values ('alice', 'allie', 'elsie', 'lisa');
insert into nicknames values ('alicia', 'allie', 'elsie', 'lisa');
insert into nicknames values ('aline', 'adeline');
insert into nicknames values ('alison', 'ali', 'allie');
insert into nicknames values ('alixandra', 'alix');
insert into nicknames values ('allan', 'al', 'alan', 'allen');
insert into nicknames values ('allen', 'al', 'alan', 'allan');
insert into nicknames values ('allisandra', 'ali', 'allie', 'ally');
insert into nicknames values ('allison', 'ali', 'allie', 'ally');
insert into nicknames values ('allyson', 'ali', 'allie', 'ally');
insert into nicknames values ('allyssa', 'ali', 'allie', 'ally');
insert into nicknames values ('almena', 'ali', 'allie', 'ally', 'mena');
insert into nicknames values ('almina', 'minnie');
insert into nicknames values ('almira', 'myra');
insert into nicknames values ('alonzo', 'al', 'lon', 'lonzo');
insert into nicknames values ('alphinias', 'alphus');
insert into nicknames values ('althea', 'ally');
insert into nicknames values ('alverta', 'vert', 'virdie');
insert into nicknames values ('alyssa', 'al', 'ally', 'lissia');
insert into nicknames values ('alzada', 'zada');
insert into nicknames values ('amanda', 'manda', 'mandy');
insert into nicknames values ('ambrose', 'brose');
insert into nicknames values ('amelia', 'amy', 'emily', 'mel', 'millie');
insert into nicknames values ('amos', 'moses');
insert into nicknames values ('anastasia', 'ana', 'stacy');
insert into nicknames values ('anderson', 'andy');
insert into nicknames values ('andre', 'drea');
insert into nicknames values ('andrea', 'andi', 'andrew', 'andy', 'drea', 'rea');
insert into nicknames values ('andrew', 'andy', 'drew', 'randy');
insert into nicknames values ('andriane', 'ada', 'adri', 'rienne');
insert into nicknames values ('angela', 'angel', 'angie');
insert into nicknames values ('angelica', 'angel', 'angelika', 'angelique', 'angie');
insert into nicknames values ('angelina', 'angel', 'angie', 'lina');
insert into nicknames values ('ann', 'annie', 'nan');
insert into nicknames values ('anna', 'ann', 'anne', 'annie', 'nan');
insert into nicknames values ('anne', 'ann', 'annie', 'nan');
insert into nicknames values ('annette', 'anna', 'nettie');
insert into nicknames values ('annie', 'ann', 'anna');
insert into nicknames values ('anselm', 'ance', 'anse', 'ansel', 'selma');
insert into nicknames values ('anthony', 'ant', 'tony');
insert into nicknames values ('antoinette', 'ann', 'netta', 'tony');
insert into nicknames values ('antonia', 'ann', 'netta', 'tony');
insert into nicknames values ('antonio', 'ant', 'tony');
insert into nicknames values ('appoline', 'appie', 'appy');
insert into nicknames values ('aquilla', 'quil', 'quillie');
insert into nicknames values ('ara', 'arry', 'belle');
insert into nicknames values ('arabella', 'ara', 'arry', 'bella', 'belle');
insert into nicknames values ('arabelle', 'ara', 'arry', 'bella', 'belle');
insert into nicknames values ('araminta', 'armida', 'middie', 'minty', 'ruminta');
insert into nicknames values ('archibald', 'archie');
insert into nicknames values ('archilles', 'kill', 'killis');
insert into nicknames values ('ariadne', 'ari', 'arie');
insert into nicknames values ('arielle', 'arie');
insert into nicknames values ('aristotle', 'telly');
insert into nicknames values ('arizona', 'ona', 'onie');
insert into nicknames values ('arlene', 'arly', 'lena');
insert into nicknames values ('armanda', 'mandy');
insert into nicknames values ('armena', 'arry', 'mena');
insert into nicknames values ('armilda', 'milly');
insert into nicknames values ('arminda', 'mindie');
insert into nicknames values ('arminta', 'minite', 'minnie');
insert into nicknames values ('arnold', 'arnie');
insert into nicknames values ('aron', 'erin', 'ron', 'ronnie');
insert into nicknames values ('artelepsa', 'epsey');
insert into nicknames values ('artemus', 'art');
insert into nicknames values ('arthur', 'art');
insert into nicknames values ('arthusa', 'thursa');
insert into nicknames values ('arzada', 'zaddi');
insert into nicknames values ('asahel', 'asa');
insert into nicknames values ('asaph', 'asa');
insert into nicknames values ('asenath', 'assene', 'natty', 'sene');
insert into nicknames values ('ashley', 'ash', 'ashly', 'leah', 'lee');
insert into nicknames values ('aubrey', 'bree');
insert into nicknames values ('audrey', 'audree', 'dee');
insert into nicknames values ('august', 'gus');
insert into nicknames values ('augusta', 'aggy', 'gatsy', 'gussie', 'tina');
insert into nicknames values ('augustina', 'aggy', 'gatsy', 'gussie', 'tina');
insert into nicknames values ('augustine', 'august', 'austin', 'gus');
insert into nicknames values ('augustus', 'august', 'austin', 'gus');
insert into nicknames values ('aurelia', 'aurilla', 'ora', 'orilla', 'ree', 'rilly');
insert into nicknames values ('avarilla', 'rilla');
insert into nicknames values ('azariah', 'aze', 'riah');
insert into nicknames values ('bab', 'barby');
insert into nicknames values ('babs', 'bab', 'barbara', 'barby');
insert into nicknames values ('barbara', 'bab', 'babs', 'barbie', 'barby', 'bobbie');
insert into nicknames values ('barbery', 'barbara');
insert into nicknames values ('barbie', 'barbara');
insert into nicknames values ('barnabas', 'barney');
insert into nicknames values ('barney', 'barnabas');
insert into nicknames values ('bart', 'bartholomew');
insert into nicknames values ('bartholomew', 'bart', 'bartel', 'bat', 'mees', 'meus');
insert into nicknames values ('barticus', 'bart');
insert into nicknames values ('bazaleel', 'basil');
insert into nicknames values ('bea', 'beatrice');
insert into nicknames values ('beatrice', 'bea', 'trisha', 'trix', 'trixie');
insert into nicknames values ('becca', 'beck');
insert into nicknames values ('beck', 'becky');
insert into nicknames values ('bedelia', 'bridgit', 'delia');
insert into nicknames values ('belinda', 'belle', 'linda');
insert into nicknames values ('bella', 'arabella', 'belle', 'isabella');
insert into nicknames values ('benedict', 'ben', 'bennie');
insert into nicknames values ('benjamin', 'ben', 'benjy', 'bennie', 'benny', 'jamie');
insert into nicknames values ('benjy', 'benjamin');
insert into nicknames values ('bernard', 'barney', 'berney', 'bernie', 'berny');
insert into nicknames values ('berney', 'bernie');
insert into nicknames values ('bert', 'bertie', 'bob', 'bobby');
insert into nicknames values ('bertha', 'bert', 'bertie', 'birdie');
insert into nicknames values ('bertram', 'bert');
insert into nicknames values ('bertrand', 'randy');
insert into nicknames values ('bess', 'bessie');
insert into nicknames values ('beth', 'betsy', 'betty', 'elizabeth');
insert into nicknames values ('bethena', 'beth', 'thaney');
insert into nicknames values ('beverly', 'bev');
insert into nicknames values ('bezaleel', 'zeely');
insert into nicknames values ('biddie', 'biddy');
insert into nicknames values ('bill', 'billy', 'fred', 'robert', 'william', 'willie');
insert into nicknames values ('billy', 'fred', 'robert', 'william');
insert into nicknames values ('blanche', 'bea');
insert into nicknames values ('bob', 'rob', 'robert');
insert into nicknames values ('bobby', 'bob', 'rob');
insert into nicknames values ('boetius', 'bo');
insert into nicknames values ('brad', 'bradford', 'ford');
insert into nicknames values ('bradford', 'brad', 'ford');
insert into nicknames values ('bradley', 'brad');
insert into nicknames values ('brady', 'brody');
insert into nicknames values ('breanna', 'bree', 'bri');
insert into nicknames values ('breeanna', 'bree');
insert into nicknames values ('brenda', 'brandy');
insert into nicknames values ('brian', 'bryan', 'bryant');
insert into nicknames values ('brianna', 'bri');
insert into nicknames values ('bridget', 'biddie', 'biddy', 'bridgie', 'bridie');
insert into nicknames values ('brittany', 'britt', 'brittnie');
insert into nicknames values ('brittney', 'britt', 'brittnie');
insert into nicknames values ('broderick', 'brady', 'brody', 'rick', 'ricky', 'rod');
insert into nicknames values ('bryanna', 'ana', 'anna', 'bri', 'briana', 'brianna');
insert into nicknames values ('caitlin', 'cait', 'caity');
insert into nicknames values ('caitlyn', 'cait', 'caity');
insert into nicknames values ('caldonia', 'calliedona');
insert into nicknames values ('caleb', 'cal');
insert into nicknames values ('california', 'callie');
insert into nicknames values ('calista', 'kissy');
insert into nicknames values ('calpurnia', 'cally');
insert into nicknames values ('calvin', 'cal', 'vin', 'vinny');
insert into nicknames values ('cameron', 'cam', 'ron', 'ronny');
insert into nicknames values ('camile', 'cammie');
insert into nicknames values ('camille', 'cammie', 'millie');
insert into nicknames values ('campbell', 'cam');
insert into nicknames values ('candace', 'candy', 'dacey');
insert into nicknames values ('carla', 'carly', 'karla');
insert into nicknames values ('carlotta', 'lottie');
insert into nicknames values ('carlton', 'carl');
insert into nicknames values ('carmellia', 'mellia');
insert into nicknames values ('carmelo', 'melo');
insert into nicknames values ('carmon', 'cammie', 'carm', 'charm');
insert into nicknames values ('carol', 'carolann', 'carole', 'caroline', 'carri', 'carrie', 'cassie', 'kara', 'kari', 'lynn');
insert into nicknames values ('carolann', 'carol', 'carole');
insert into nicknames values ('caroline', 'carol', 'carole', 'carrie', 'cassie', 'lynn');
insert into nicknames values ('carolyn', 'carrie', 'cassie', 'lynn');
insert into nicknames values ('carrie', 'cassie');
insert into nicknames values ('carthaette', 'etta', 'etty');
insert into nicknames values ('casey', 'k.c.');
insert into nicknames values ('casper', 'jasper');
insert into nicknames values ('cassandra', 'cassie', 'sandra', 'sandy');
insert into nicknames values ('cassidy', 'cass', 'cassie');
insert into nicknames values ('caswell', 'cass');
insert into nicknames values ('catherine', 'casey', 'cassie', 'cathy', 'kathy', 'katy', 'kay', 'kit', 'kittie', 'lena', 'trina');
insert into nicknames values ('cathleen', 'casey', 'cassie', 'cathy', 'kathy', 'katy', 'kay', 'kit', 'kittie', 'lena', 'trina');
insert into nicknames values ('cathy', 'catherine', 'cathleen', 'kathy');
insert into nicknames values ('cecilia', 'celia', 'cissy');
insert into nicknames values ('cedric', 'ced', 'rick', 'ricky');
insert into nicknames values ('celeste', 'celia', 'lessie');
insert into nicknames values ('celinda', 'linda', 'lindy', 'lynn');
insert into nicknames values ('charity', 'chat');
insert into nicknames values ('charles', 'carl', 'charlie', 'chick', 'chuck');
insert into nicknames values ('charlie', 'charles', 'chuck');
insert into nicknames values ('charlotte', 'char', 'lotta', 'lottie', 'sherry');
insert into nicknames values ('chauncey', 'chan');
insert into nicknames values ('chelsey', 'chelsie');
insert into nicknames values ('cheryl', 'cher');
insert into nicknames values ('chesley', 'chet');
insert into nicknames values ('chester', 'chet');
insert into nicknames values ('chet', 'chester');
insert into nicknames values ('chick', 'caroline', 'charlotte', 'chuck');
insert into nicknames values ('chloe', 'clo');
insert into nicknames values ('chris', 'kris');
insert into nicknames values ('christa', 'chris');
insert into nicknames values ('christian', 'chris', 'kit');
insert into nicknames values ('christiana', 'ann', 'chris', 'christy', 'crissy', 'kris', 'kristy', 'tina');
insert into nicknames values ('christiano', 'chris');
insert into nicknames values ('christina', 'chris', 'chrissy', 'christy', 'crissy', 'kris', 'kristy', 'tina');
insert into nicknames values ('christine', 'chris', 'chrissy', 'christy', 'crissy', 'kris', 'kristy', 'tina');
insert into nicknames values ('christoffer', 'chris');
insert into nicknames values ('christoph', 'chris');
insert into nicknames values ('christopher', 'chris', 'kit');
insert into nicknames values ('christy', 'crissy');
insert into nicknames values ('cicely', 'cilla');
insert into nicknames values ('cinderella', 'arilla', 'cindy', 'rella', 'rilla');
insert into nicknames values ('cindy', 'cinderella');
insert into nicknames values ('claire', 'clair', 'clara', 'clare');
insert into nicknames values ('clara', 'clarissa');
insert into nicknames values ('clare', 'clara');
insert into nicknames values ('clarence', 'clair', 'clare');
insert into nicknames values ('clarinda', 'clara');
insert into nicknames values ('clarissa', 'cissy', 'clara');
insert into nicknames values ('claudia', 'claud');
insert into nicknames values ('cleatus', 'cleat');
insert into nicknames values ('clement', 'clem');
insert into nicknames values ('clementine', 'clem', 'clement');
insert into nicknames values ('cliff', 'clifford');
insert into nicknames values ('clifford', 'cliff', 'ford');
insert into nicknames values ('clifton', 'cliff', 'tony');
insert into nicknames values ('cole', 'colie');
insert into nicknames values ('columbus', 'clum');
insert into nicknames values ('con', 'conny');
insert into nicknames values ('conrad', 'con', 'conny');
insert into nicknames values ('constance', 'connie');
insert into nicknames values ('cordelia', 'cordy', 'delia');
insert into nicknames values ('corey', 'coco', 'cordy', 'ree');
insert into nicknames values ('corinne', 'cora', 'ora');
insert into nicknames values ('cornelia', 'cornie', 'corny', 'nelia', 'nelle', 'nelly');
insert into nicknames values ('cornelius', 'con', 'conny', 'corny', 'neil', 'niel');
insert into nicknames values ('cory', 'coco', 'cordy', 'ree');
insert into nicknames values ('courtney', 'court', 'curt');
insert into nicknames values ('crystal', 'chris', 'crys', 'stal', 'tal');
insert into nicknames values ('curtis', 'curt');
insert into nicknames values ('cynthia', 'cindy', 'cintha');
insert into nicknames values ('cyrenius', 'cene', 'cy', 'renius', 'serene', 'swene');
insert into nicknames values ('cyrus', 'cy');
insert into nicknames values ('dahl', 'dal');
insert into nicknames values ('dalton', 'dahl', 'dal');
insert into nicknames values ('daniel', 'dan', 'dann', 'danny');
insert into nicknames values ('danielle', 'dani', 'ellie');
insert into nicknames values ('danny', 'daniel');
insert into nicknames values ('daphne', 'daph', 'daphie');
insert into nicknames values ('darlene', 'darry', 'lena');
insert into nicknames values ('david', 'dave', 'davey', 'day');
insert into nicknames values ('daycia', 'dacia', 'daisha');
insert into nicknames values ('deanne', 'ann', 'dee');
insert into nicknames values ('debbie', 'deb', 'debby', 'deborah', 'debra');
insert into nicknames values ('debby', 'deb');
insert into nicknames values ('debora', 'deb', 'debbie', 'debby');
insert into nicknames values ('deborah', 'deb', 'debbie', 'debby');
insert into nicknames values ('debra', 'deb', 'debbie');
insert into nicknames values ('deidre', 'deedee');
insert into nicknames values ('delbert', 'bert', 'del');
insert into nicknames values ('delia', 'cordelia', 'delius', 'fidelia');
insert into nicknames values ('delilah', 'dell', 'della', 'lil', 'lila');
insert into nicknames values ('deliverance', 'della', 'delly', 'dilly');
insert into nicknames values ('della', 'adela', 'adelaide', 'delilah', 'dell');
insert into nicknames values ('delores', 'dee', 'dell', 'della', 'lola', 'lolly');
insert into nicknames values ('delpha', 'philadelphia');
insert into nicknames values ('delphine', 'del', 'delf', 'delphi');
insert into nicknames values ('demaris', 'dea', 'maris', 'mary');
insert into nicknames values ('demerias', 'dea', 'maris', 'mary');
insert into nicknames values ('democrates', 'mock');
insert into nicknames values ('dennis', 'dennie', 'denny');
insert into nicknames values ('dennison', 'dennis', 'denny');
insert into nicknames values ('derek', 'derrek', 'rick', 'ricky');
insert into nicknames values ('derick', 'rick', 'ricky');
insert into nicknames values ('derrick', 'eric', 'rick', 'ricky');
insert into nicknames values ('deuteronomy', 'duty');
insert into nicknames values ('diana', 'di', 'dicey', 'didi');
insert into nicknames values ('diane', 'di', 'dian', 'dianne', 'dicey', 'didi');
insert into nicknames values ('dicey', 'dicie');
insert into nicknames values ('dick', 'richard', 'rick');
insert into nicknames values ('dickson', 'dick');
insert into nicknames values ('domenic', 'dom', 'nic');
insert into nicknames values ('dominic', 'dom', 'nic');
insert into nicknames values ('dominick', 'dom', 'nick', 'nicky');
insert into nicknames values ('dominico', 'dom');
insert into nicknames values ('donald', 'don', 'donnie', 'donny', 'dony');
insert into nicknames values ('donato', 'don');
insert into nicknames values ('donna', 'dona');
insert into nicknames values ('donovan', 'don', 'donnie', 'donny', 'dony');
insert into nicknames values ('dorcus', 'darkey');
insert into nicknames values ('dorinda', 'dora', 'dorothea');
insert into nicknames values ('doris', 'dora');
insert into nicknames values ('dorothea', 'doda', 'dora');
insert into nicknames values ('dorothy', 'dolly', 'dora', 'dortha', 'dot', 'dottie', 'dotty');
insert into nicknames values ('dotha', 'dotty');
insert into nicknames values ('dotty', 'dot');
insert into nicknames values ('douglas', 'doug');
insert into nicknames values ('drusilla', 'silla');
insert into nicknames values ('duncan', 'dunk');
insert into nicknames values ('earnest', 'ernestine', 'ernie');
insert into nicknames values ('ebbie', 'eb');
insert into nicknames values ('ebenezer', 'eb', 'ebbie', 'eben');
insert into nicknames values ('eddie', 'ed');
insert into nicknames values ('eddy', 'ed');
insert into nicknames values ('edgar', 'ed', 'eddie', 'eddy');
insert into nicknames values ('edith', 'edie', 'edye');
insert into nicknames values ('edmond', 'ed', 'eddie', 'eddy');
insert into nicknames values ('edmund', 'ed', 'eddie', 'eddy', 'ned', 'ted');
insert into nicknames values ('edna', 'edny');
insert into nicknames values ('eduardo', 'ed', 'eddie', 'eddy');
insert into nicknames values ('edward', 'ed', 'eddie', 'eddy', 'ned', 'ted', 'teddy');
insert into nicknames values ('edwin', 'ed', 'eddie', 'eddy', 'ned', 'win');
insert into nicknames values ('edwina', 'edwin');
insert into nicknames values ('edyth', 'edie', 'edye');
insert into nicknames values ('edythe', 'edie', 'edye');
insert into nicknames values ('egbert', 'bert', 'burt');
insert into nicknames values ('eighta', 'athy');
insert into nicknames values ('eileen', 'helen');
insert into nicknames values ('elaine', 'helen', 'lainie');
insert into nicknames values ('elbert', 'albert', 'bert');
insert into nicknames values ('elbertson', 'bert', 'elbert');
insert into nicknames values ('eldora', 'dora');
insert into nicknames values ('eleanor', 'elaine', 'ellen', 'ellie', 'lanna', 'lenora', 'nelly', 'nora');
insert into nicknames values ('eleazer', 'lazar');
insert into nicknames values ('elena', 'helen');
insert into nicknames values ('elias', 'eli', 'lee', 'lias');
insert into nicknames values ('elijah', 'eli', 'lige');
insert into nicknames values ('eliphalel', 'life');
insert into nicknames values ('eliphalet', 'left');
insert into nicknames values ('elisa', 'lisa');
insert into nicknames values ('elisha', 'eli', 'lish');
insert into nicknames values ('eliza', 'elizabeth');
insert into nicknames values ('elizabeth', 'bess', 'bessie', 'beth', 'betsy', 'betty', 'eliza', 'lib', 'libby', 'lisa', 'liz', 'liza', 'lizzie', 'lizzy');
insert into nicknames values ('ella', 'el', 'ellen');
insert into nicknames values ('ellen', 'helen', 'nell', 'nellie');
insert into nicknames values ('ellender', 'ellen', 'helen', 'nellie');
insert into nicknames values ('ellie', 'elly');
insert into nicknames values ('ellswood', 'elsey');
insert into nicknames values ('elminie', 'minnie');
insert into nicknames values ('elmira', 'ellie', 'elly', 'mira');
insert into nicknames values ('elnora', 'nora');
insert into nicknames values ('eloise', 'heloise', 'louise');
insert into nicknames values ('elouise', 'louise');
insert into nicknames values ('elsie', 'elsey');
insert into nicknames values ('elswood', 'elsey');
insert into nicknames values ('elvira', 'elvie');
insert into nicknames values ('elwood', 'woody');
insert into nicknames values ('elysia', 'lisa', 'lissa');
insert into nicknames values ('elze', 'elsey');
insert into nicknames values ('emanuel', 'manny', 'manuel');
insert into nicknames values ('emeline', 'em', 'emily', 'emma', 'emmy', 'milly');
insert into nicknames values ('emil', 'em', 'emily');
insert into nicknames values ('emily', 'em', 'emma', 'emmy', 'mel', 'millie');
insert into nicknames values ('emma', 'em', 'emmy');
insert into nicknames values ('epaphroditius', 'dite', 'ditus', 'dyce', 'dyche', 'eppa');
insert into nicknames values ('ephraim', 'eph');
insert into nicknames values ('erasmus', 'rasmus', 'raze');
insert into nicknames values ('eric', 'rick', 'ricky');
insert into nicknames values ('ernest', 'ernie');
insert into nicknames values ('ernestine', 'erna', 'ernest', 'teeny', 'tina');
insert into nicknames values ('erwin', 'irwin');
insert into nicknames values ('eseneth', 'senie');
insert into nicknames values ('essy', 'es');
insert into nicknames values ('estella', 'essy', 'stella');
insert into nicknames values ('estelle', 'essy', 'stella');
insert into nicknames values ('esther', 'essie', 'hester');
insert into nicknames values ('eudicy', 'dicey');
insert into nicknames values ('eudora', 'dora');
insert into nicknames values ('eudoris', 'dosie', 'dossie');
insert into nicknames values ('eugene', 'gene');
insert into nicknames values ('eunice', 'nicie');
insert into nicknames values ('euphemia', 'effie', 'effy');
insert into nicknames values ('eurydice', 'dicey');
insert into nicknames values ('eustacia', 'stacia', 'stacy');
insert into nicknames values ('eva', 'eve');
insert into nicknames values ('evaline', 'eva', 'eve', 'lena');
insert into nicknames values ('evangeline', 'ev', 'evan', 'vangie');
insert into nicknames values ('evelyn', 'ev', 'eve', 'evelina');
insert into nicknames values ('experience', 'exie');
insert into nicknames values ('ezekiel', 'ez', 'zeke');
insert into nicknames values ('ezideen', 'ez');
insert into nicknames values ('ezra', 'ez');
insert into nicknames values ('faith', 'fay');
insert into nicknames values ('fallon', 'fal', 'falcon', 'fall', 'fallie', 'fally', 'falon', 'lon', 'lonnie');
insert into nicknames values ('felicia', 'fel', 'feli', 'felix');
insert into nicknames values ('felicity', 'flick', 'tick');
insert into nicknames values ('feltie', 'felty');
insert into nicknames values ('ferdinand', 'ferdie', 'fred', 'freddie', 'freddy');
insert into nicknames values ('ferdinando', 'ferdie', 'fred', 'nando');
insert into nicknames values ('fidelia', 'delia');
insert into nicknames values ('fionna', 'fiona');
insert into nicknames values ('flora', 'florence');
insert into nicknames values ('florence', 'flo', 'flora', 'flossy');
insert into nicknames values ('floyd', 'lloyd');
insert into nicknames values ('fran', 'frannie');
insert into nicknames values ('frances', 'cissy', 'fanny', 'fran', 'francie', 'frankie', 'frannie', 'franniey', 'franny', 'sis');
insert into nicknames values ('francie', 'francine');
insert into nicknames values ('francine', 'fran', 'francie', 'frannie', 'franniey', 'franny');
insert into nicknames values ('francis', 'fran', 'frank', 'frankie');
insert into nicknames values ('frankie', 'francis', 'frank');
insert into nicknames values ('franklin', 'fran', 'frank');
insert into nicknames values ('franklind', 'fran', 'frank');
insert into nicknames values ('freda', 'frieda');
insert into nicknames values ('frederica', 'erica', 'erika', 'freddy', 'frederick', 'rickey');
insert into nicknames values ('frederick', 'derick', 'erick', 'fred', 'freddie', 'freddy', 'fritz', 'rick', 'ricky');
insert into nicknames values ('fredericka', 'ericka', 'freda', 'freddy', 'frieda', 'ricka', 'rickey');
insert into nicknames values ('frieda', 'fred', 'freddie', 'freddy');
insert into nicknames values ('gabriel', 'gabby', 'gabe');
insert into nicknames values ('gabriella', 'ella', 'gabby');
insert into nicknames values ('gabrielle', 'ella', 'gabby');
insert into nicknames values ('gareth', 'gare', 'gary');
insert into nicknames values ('garrett', 'barrett', 'gare', 'garratt', 'garret', 'garry', 'gary', 'jerry', 'rhett');
insert into nicknames values ('garrick', 'garri');
insert into nicknames values ('genevieve', 'eve', 'jean', 'jenny');
insert into nicknames values ('geoffrey', 'geoff', 'jeff');
insert into nicknames values ('george', 'georgie');
insert into nicknames values ('georgiana', 'georgia');
insert into nicknames values ('georgine', 'george');
insert into nicknames values ('gerald', 'gerry', 'jerry');
insert into nicknames values ('geraldine', 'dina', 'gerri', 'gerrie', 'gerry', 'jerry');
insert into nicknames values ('gerhardt', 'gay');
insert into nicknames values ('gertie', 'gert', 'gertrude');
insert into nicknames values ('gertrude', 'gert', 'gertie', 'trudy');
insert into nicknames values ('gilbert', 'bert', 'gil', 'wilber');
insert into nicknames values ('giovanni', 'gio');
insert into nicknames values ('glenn', 'glen');
insert into nicknames values ('gloria', 'glory');
insert into nicknames values ('governor', 'govie');
insert into nicknames values ('greenberry', 'berry', 'green');
insert into nicknames values ('greggory', 'gregg');
insert into nicknames values ('gregory', 'gory', 'greg');
insert into nicknames values ('gretchen', 'margaret');
insert into nicknames values ('griselda', 'grissel');
insert into nicknames values ('gum', 'monty');
insert into nicknames values ('gus', 'gussie');
insert into nicknames values ('gustavus', 'gus', 'gussie');
insert into nicknames values ('gwen', 'wendy');
insert into nicknames values ('gwendolyn', 'gwen', 'wendy');
insert into nicknames values ('hailey', 'haylee', 'hayley');
insert into nicknames values ('hamilton', 'ham');
insert into nicknames values ('hannah', 'anna', 'nan', 'nanny');
insert into nicknames values ('harold', 'hal', 'hap', 'haps', 'harry');
insert into nicknames values ('harriet', 'hattie');
insert into nicknames values ('harrison', 'hap', 'haps', 'harry');
insert into nicknames values ('harry', 'hap', 'haps', 'harold', 'henry');
insert into nicknames values ('haseltine', 'hassie');
insert into nicknames values ('haylee', 'hailey', 'hayley');
insert into nicknames values ('hayley', 'hailey', 'haylee');
insert into nicknames values ('heather', 'hetty');
insert into nicknames values ('helen', 'ella', 'ellen', 'ellie', 'lena');
insert into nicknames values ('helena', 'aileen', 'eileen', 'elaine', 'eleanor', 'ellen', 'lena', 'nell', 'nellie');
insert into nicknames values ('helene', 'ella', 'ellen', 'ellie', 'lena');
insert into nicknames values ('heloise', 'eloise', 'elouise', 'lois');
insert into nicknames values ('henrietta', 'etta', 'etty', 'hank', 'henny', 'nettie', 'retta');
insert into nicknames values ('henry', 'hal', 'hank', 'hap', 'haps', 'harry');
insert into nicknames values ('hephsibah', 'hipsie');
insert into nicknames values ('hepsibah', 'hipsie');
insert into nicknames values ('herbert', 'bert', 'herb');
insert into nicknames values ('herman', 'dutch', 'harman');
insert into nicknames values ('hermione', 'hermie');
insert into nicknames values ('hester', 'esther', 'hessy', 'hetty');
insert into nicknames values ('hezekiah', 'hez', 'hy', 'kiah');
insert into nicknames values ('hillary', 'hilary');
insert into nicknames values ('hipsbibah', 'hipsie');
insert into nicknames values ('hiram', 'hy');
insert into nicknames values ('honora', 'honey', 'nora', 'norah', 'norry');
insert into nicknames values ('hopkins', 'hop', 'hopp');
insert into nicknames values ('horace', 'horry');
insert into nicknames values ('hortense', 'harty', 'tensey');
insert into nicknames values ('hosea', 'hosey', 'hosie');
insert into nicknames values ('howard', 'hal', 'howie');
insert into nicknames values ('hubert', 'bert', 'hub', 'hugh');
insert into nicknames values ('ian', 'john');
insert into nicknames values ('ignatius', 'iggy', 'nace', 'nate', 'natius');
insert into nicknames values ('ignatzio', 'iggy', 'nace', 'naz');
insert into nicknames values ('immanuel', 'emmanuel', 'manuel');
insert into nicknames values ('india', 'indie', 'indy');
insert into nicknames values ('inez', 'agnes');
insert into nicknames values ('iona', 'onnie');
insert into nicknames values ('irene', 'rena');
insert into nicknames values ('irvin', 'irving');
insert into nicknames values ('irving', 'irv');
insert into nicknames values ('irwin', 'erwin');
insert into nicknames values ('isaac', 'ike', 'zeke');
insert into nicknames values ('isabel', 'bell', 'bella', 'belle', 'ib', 'issy', 'nib', 'nibby', 'tibbie');
insert into nicknames values ('isabella', 'bella', 'belle', 'ib', 'issy', 'nib', 'nibby', 'tibbie');
insert into nicknames values ('isabelle', 'bella', 'belle', 'ib', 'issy', 'nib', 'nibby', 'tibbie');
insert into nicknames values ('isadora', 'dora', 'issy');
insert into nicknames values ('isadore', 'izzy');
insert into nicknames values ('isaiah', 'zadie', 'zay');
insert into nicknames values ('isidore', 'izzy');
insert into nicknames values ('iva', 'ivy');
insert into nicknames values ('ivan', 'john');
insert into nicknames values ('jackson', 'jack');
insert into nicknames values ('jacob', 'jaap', 'jake', 'jay');
insert into nicknames values ('jacobus', 'jacob');
insert into nicknames values ('jacqueline', 'jack', 'jackie', 'jacqui');
insert into nicknames values ('jahoda', 'hoda', 'hodie', 'hody');
insert into nicknames values ('jakob', 'jake');
insert into nicknames values ('jalen', 'al', 'alen', 'haylen', 'jaelin', 'jaelyn', 'jailyn', 'jay', 'jaye', 'jaylin', 'jaylyn', 'len', 'lennie', 'lenny');
insert into nicknames values ('james', 'jamie', 'jem', 'jim', 'jimmie', 'jimmy');
insert into nicknames values ('jamey', 'james', 'jamie');
insert into nicknames values ('jamie', 'james');
insert into nicknames values ('jane', 'janie', 'jean', 'jennie', 'jessie');
insert into nicknames values ('janet', 'jan', 'jessie');
insert into nicknames values ('janice', 'jan');
insert into nicknames values ('jannett', 'nettie');
insert into nicknames values ('jasper', 'casper', 'jap');
insert into nicknames values ('jayme', 'jay');
insert into nicknames values ('jean', 'jane', 'jeannie');
insert into nicknames values ('jeanette', 'janet', 'jean', 'jessie', 'nettie');
insert into nicknames values ('jeanne', 'jane', 'jeannie');
insert into nicknames values ('jebadiah', 'jeb');
insert into nicknames values ('jedediah', 'diah', 'dyer', 'jed');
insert into nicknames values ('jedidiah', 'diah', 'dyer', 'jed');
insert into nicknames values ('jefferey', 'jeff');
insert into nicknames values ('jefferson', 'jeff', 'sonny');
insert into nicknames values ('jeffery', 'jeff');
insert into nicknames values ('jeffrey', 'geoff', 'jeff');
insert into nicknames values ('jehiel', 'hiel');
insert into nicknames values ('jehu', 'gee', 'hugh');
insert into nicknames values ('jemima', 'mima');
insert into nicknames values ('jennet', 'jenn', 'jenny', 'jessie');
insert into nicknames values ('jennifer', 'jen', 'jenn', 'jenni', 'jennie', 'jenny');
insert into nicknames values ('jeremiah', 'jereme', 'jerry');
insert into nicknames values ('jeremy', 'jez', 'jezza');
insert into nicknames values ('jerita', 'rita');
insert into nicknames values ('jerry', 'geraldine', 'geri', 'gerry', 'jereme');
insert into nicknames values ('jessica', 'jess', 'jessie');
insert into nicknames values ('jessie', 'jane', 'janet', 'jess');
insert into nicknames values ('jillian', 'jill');
insert into nicknames values ('jim', 'jimmie');
insert into nicknames values ('jincy', 'jane');
insert into nicknames values ('jinsy', 'jane');
insert into nicknames values ('joan', 'jo', 'nonie');
insert into nicknames values ('joann', 'jo');
insert into nicknames values ('joanna', 'hannah', 'jo', 'joan', 'jodi', 'jody');
insert into nicknames values ('joanne', 'jo');
insert into nicknames values ('jody', 'jo');
insert into nicknames values ('joe', 'joey');
insert into nicknames values ('johann', 'john');
insert into nicknames values ('johanna', 'jo');
insert into nicknames values ('johannah', 'hannah', 'jo', 'joan', 'jody', 'nonie');
insert into nicknames values ('johannes', 'john', 'johnny', 'jonathan');
insert into nicknames values ('john', 'ian', 'jack', 'jock', 'johnny', 'jon', 'jonnie', 'jonny');
insert into nicknames values ('johnathan', 'john', 'johnathon', 'johny', 'jon', 'jonathan', 'jonathon', 'jonnie', 'jonny', 'nathan');
insert into nicknames values ('johnathon', 'john', 'johnathan', 'johny', 'jon', 'jonathan', 'jonathon', 'jonnie', 'jonny');
insert into nicknames values ('jon', 'john', 'johnny', 'jonnie', 'jonny');
insert into nicknames values ('jonathan', 'john', 'johnathan', 'johnathon', 'johny', 'jon', 'jonathon', 'jonnie', 'jonny', 'nathan');
insert into nicknames values ('jonathon', 'john', 'johnathan', 'johnathon', 'johny', 'jon', 'jonathan', 'jonnie', 'jonny');
insert into nicknames values ('joseph', 'jody', 'joe', 'joey', 'jos');
insert into nicknames values ('josephine', 'fina', 'jo', 'jody', 'joey', 'josey', 'josie');
insert into nicknames values ('josetta', 'jettie');
insert into nicknames values ('josey', 'josophine');
insert into nicknames values ('joshua', 'joe', 'jos', 'josh');
insert into nicknames values ('josiah', 'jos');
insert into nicknames values ('josophine', 'jo', 'joey', 'josey');
insert into nicknames values ('joyce', 'joy');
insert into nicknames values ('juanita', 'nettie', 'nita');
insert into nicknames values ('judah', 'jude', 'juder');
insert into nicknames values ('judith', 'juda', 'jude', 'judi', 'judie', 'judy');
insert into nicknames values ('judson', 'jud', 'sonny');
insert into nicknames values ('judy', 'judith');
insert into nicknames values ('julia', 'jill', 'jules', 'julie');
insert into nicknames values ('julian', 'jule', 'jules');
insert into nicknames values ('julias', 'jule', 'jules');
insert into nicknames values ('julie', 'jule', 'jules', 'julia');
insert into nicknames values ('june', 'junius');
insert into nicknames values ('junior', 'jr', 'june', 'junie');
insert into nicknames values ('justin', 'justina', 'juston', 'justus');
insert into nicknames values ('kaitlin', 'kait', 'kaitie');
insert into nicknames values ('kaitlyn', 'kait', 'kaitie');
insert into nicknames values ('kaitlynn', 'kait', 'kaitie');
insert into nicknames values ('kalli', 'cali', 'kali');
insert into nicknames values ('kameron', 'kam');
insert into nicknames values ('karla', 'carla', 'carly');
insert into nicknames values ('kasey', 'k.c.');
insert into nicknames values ('katarina', 'catherine', 'tina');
insert into nicknames values ('kate', 'kay');
insert into nicknames values ('katelin', 'kate', 'kay', 'kaye');
insert into nicknames values ('katelyn', 'kate', 'kay', 'kaye');
insert into nicknames values ('katherine', 'cassie', 'cathy', 'kate', 'kathy', 'katy', 'kay', 'kaye', 'kit', 'kittie', 'lena', 'trina');
insert into nicknames values ('kathleen', 'cassie', 'cathy', 'kathy', 'katy', 'kay', 'kit', 'kittie', 'lena', 'trina');
insert into nicknames values ('kathryn', 'kate', 'kathy', 'katie');
insert into nicknames values ('katia', 'kate', 'katie');
insert into nicknames values ('katy', 'kate', 'kathy', 'katie');
insert into nicknames values ('kayla', 'kay');
insert into nicknames values ('kelley', 'kelli', 'kellie', 'kelly');
insert into nicknames values ('kendall', 'ken', 'kenny');
insert into nicknames values ('kendra', 'kay', 'kenj', 'kenji', 'kenny');
insert into nicknames values ('kendrick', 'ken', 'kenny');
insert into nicknames values ('kendrik', 'ken', 'kenny');
insert into nicknames values ('kenneth', 'ken', 'kendrick', 'kenny');
insert into nicknames values ('kenny', 'ken', 'kenneth');
insert into nicknames values ('kent', 'ken', 'kendrick', 'kenny');
insert into nicknames values ('kerry', 'kerri');
insert into nicknames values ('kevin', 'kev');
insert into nicknames values ('keziah', 'kizza', 'kizzie');
insert into nicknames values ('kimberley', 'kim', 'kimberli', 'kimberly');
insert into nicknames values ('kimberly', 'kim', 'kimberley', 'kimberli');
insert into nicknames values ('kingsley', 'king');
insert into nicknames values ('kingston', 'king');
insert into nicknames values ('kit', 'kittie');
insert into nicknames values ('kris', 'chris');
insert into nicknames values ('kristel', 'kris');
insert into nicknames values ('kristen', 'chris');
insert into nicknames values ('kristin', 'chris');
insert into nicknames values ('kristine', 'chris', 'christy', 'crissy', 'kris', 'kristy', 'tina');
insert into nicknames values ('kristofer', 'chris', 'kris');
insert into nicknames values ('kristoffer', 'chris', 'kris');
insert into nicknames values ('kristopher', 'chris', 'kris');
insert into nicknames values ('kristy', 'chris');
insert into nicknames values ('kymberly', 'kym');
insert into nicknames values ('lafayette', 'fate', 'laffie');
insert into nicknames values ('lamont', 'monty');
insert into nicknames values ('laodicia', 'cenia', 'dicy');
insert into nicknames values ('larry', 'laurence', 'lawrence');
insert into nicknames values ('latisha', 'tish', 'tisha');
insert into nicknames values ('laurel', 'laurie');
insert into nicknames values ('lauren', 'laurie', 'ren');
insert into nicknames values ('laurence', 'larry', 'lon', 'lonny', 'lorne', 'lorry');
insert into nicknames values ('laurinda', 'laura', 'lawrence');
insert into nicknames values ('lauryn', 'laurie');
insert into nicknames values ('laveda', 'veda');
insert into nicknames values ('laverne', 'verna', 'vernon');
insert into nicknames values ('lavina', 'ina', 'vina', 'viney');
insert into nicknames values ('lavinia', 'ina', 'vina', 'viney');
insert into nicknames values ('lavonia', 'vina', 'viney', 'vonnie', 'wyncha');
insert into nicknames values ('lavonne', 'von');
insert into nicknames values ('lawrence', 'larry', 'lawrie', 'lon', 'lonny', 'lorne', 'lorry');
insert into nicknames values ('leanne', 'annie', 'lea');
insert into nicknames values ('lecurgus', 'curg');
insert into nicknames values ('leilani', 'lani');
insert into nicknames values ('lemuel', 'lem');
insert into nicknames values ('lena', 'ellen');
insert into nicknames values ('lenora', 'lee', 'nora');
insert into nicknames values ('leo', 'leon');
insert into nicknames values ('leonard', 'len', 'lenny', 'leo', 'leon', 'lineau');
insert into nicknames values ('leonidas', 'lee', 'leon');
insert into nicknames values ('leonora', 'nell', 'nellie', 'nora');
insert into nicknames values ('leonore', 'elenor', 'honor', 'nora');
insert into nicknames values ('leroy', 'l.r.', 'lee', 'roy');
insert into nicknames values ('lesley', 'les');
insert into nicknames values ('leslie', 'les');
insert into nicknames values ('lester', 'les');
insert into nicknames values ('letitia', 'lettice', 'lettie', 'tish', 'titia');
insert into nicknames values ('levi', 'lee');
insert into nicknames values ('levicy', 'vicy');
insert into nicknames values ('levone', 'von');
insert into nicknames values ('lib', 'libby');
insert into nicknames values ('lidia', 'lyddy');
insert into nicknames values ('lil', 'lilly', 'lily');
insert into nicknames values ('lillah', 'lil', 'lilly', 'lily', 'lolly');
insert into nicknames values ('lillian', 'lil', 'lilly', 'lolly');
insert into nicknames values ('lilly', 'lil', 'lily');
insert into nicknames values ('lincoln', 'link');
insert into nicknames values ('linda', 'lindy', 'lynn');
insert into nicknames values ('lindsay', 'lindsey', 'lindsie', 'lindsy');
insert into nicknames values ('lindy', 'lynn');
insert into nicknames values ('lionel', 'leon');
insert into nicknames values ('lisa', 'liz');
insert into nicknames values ('littleberry', 'berry', 'l.b.', 'little');
insert into nicknames values ('lizzie', 'liz');
insert into nicknames values ('lois', 'lou', 'louise');
insert into nicknames values ('lonzo', 'lon');
insert into nicknames values ('lorelei', 'laurie', 'lori', 'lorrie');
insert into nicknames values ('lorenzo', 'loren');
insert into nicknames values ('loretta', 'etta', 'lorie', 'lorrie', 'retta');
insert into nicknames values ('lorraine', 'lorie', 'lorrie');
insert into nicknames values ('lotta', 'lottie');
insert into nicknames values ('lou', 'louis', 'lu');
insert into nicknames values ('louis', 'lewis', 'lou', 'louie', 'louise');
insert into nicknames values ('louisa', 'eliza', 'lois', 'lou');
insert into nicknames values ('louise', 'eliza', 'lois', 'lou');
insert into nicknames values ('louvinia', 'vina', 'viney', 'vonnie', 'wyncha');
insert into nicknames values ('lucas', 'luke');
insert into nicknames values ('lucia', 'lucius', 'lucy');
insert into nicknames values ('lucias', 'luke');
insert into nicknames values ('lucille', 'cille', 'lou', 'lu', 'lucy');
insert into nicknames values ('lucina', 'sinah');
insert into nicknames values ('lucinda', 'cindy', 'lou', 'lu', 'lucy');
insert into nicknames values ('lucretia', 'creasey');
insert into nicknames values ('lucy', 'lucinda');
insert into nicknames values ('luella', 'ella', 'lu', 'lula');
insert into nicknames values ('luke', 'lucas');
insert into nicknames values ('lunetta', 'nettie');
insert into nicknames values ('lurana', 'lura');
insert into nicknames values ('luther', 'luke');
insert into nicknames values ('lydia', 'lyddy');
insert into nicknames values ('lyndon', 'lindy', 'lynn');
insert into nicknames values ('mabel', 'amabel', 'mehitabel');
insert into nicknames values ('mac', 'mc');
insert into nicknames values ('mack', 'mac', 'mc');
insert into nicknames values ('mackenzie', 'kenzy', 'mac', 'mack');
insert into nicknames values ('maddison', 'maddi', 'maddie');
insert into nicknames values ('maddy', 'madeline', 'madelyn', 'madge');
insert into nicknames values ('madeline', 'lena', 'maddi', 'maddie', 'maddy', 'madge', 'madie', 'magda', 'maggie', 'maud');
insert into nicknames values ('madelyn', 'maddy', 'madie');
insert into nicknames values ('madie', 'madeline', 'madelyn');
insert into nicknames values ('madison', 'maddy', 'mattie');
insert into nicknames values ('maegen', 'meg');
insert into nicknames values ('magdalena', 'lena', 'maggie');
insert into nicknames values ('magdelina', 'lena', 'madge', 'magda', 'maggie');
insert into nicknames values ('mahala', 'hallie');
insert into nicknames values ('makayla', 'kayla');
insert into nicknames values ('malachi', 'mally');
insert into nicknames values ('malcolm', 'mac', 'mal', 'malc');
insert into nicknames values ('malinda', 'lindy');
insert into nicknames values ('manda', 'mandy');
insert into nicknames values ('mandie', 'amanda');
insert into nicknames values ('mandy', 'amanda');
insert into nicknames values ('manerva', 'eve', 'minerva', 'nerva', 'nervie');
insert into nicknames values ('manny', 'manuel');
insert into nicknames values ('manoah', 'noah');
insert into nicknames values ('manola', 'nonnie');
insert into nicknames values ('manuel', 'emanuel', 'manny');
insert into nicknames values ('marcus', 'marc', 'mark');
insert into nicknames values ('margaret', 'daisy', 'gretta', 'madge', 'maggie', 'maggy', 'marge', 'margery', 'margie', 'margy', 'meg', 'midge', 'peg', 'peggy', 'rita');
insert into nicknames values ('margaretta', 'daisy', 'gretta', 'madge', 'maggie', 'marge', 'margery', 'margie', 'meg', 'midge', 'peg', 'peggy', 'rita');
insert into nicknames values ('margarita', 'daisy', 'greta', 'madge', 'maggie', 'maisie', 'marge', 'margo', 'meg', 'megan', 'metta', 'midge', 'peggie', 'rita');
insert into nicknames values ('marge', 'margaret', 'margaretta', 'margery');
insert into nicknames values ('margie', 'marjorie');
insert into nicknames values ('marguerite', 'peggy');
insert into nicknames values ('mariah', 'maria', 'mary');
insert into nicknames values ('marian', 'marianna', 'marion');
insert into nicknames values ('marie', 'mae', 'mary');
insert into nicknames values ('marietta', 'mae', 'mamie', 'maria', 'mariah', 'marie', 'marion', 'mary', 'maureen', 'may', 'mercy', 'minnie', 'mitzi', 'mollie', 'molly', 'polly');
insert into nicknames values ('marilyn', 'mary');
insert into nicknames values ('marion', 'mary');
insert into nicknames values ('marissa', 'rissa');
insert into nicknames values ('marjorie', 'margie', 'margy');
insert into nicknames values ('marni', 'marnie');
insert into nicknames values ('marsha', 'marcia', 'marcie', 'mary');
insert into nicknames values ('martha', 'marty', 'mat', 'mattie', 'patsy', 'patty');
insert into nicknames values ('martin', 'marty');
insert into nicknames values ('martina', 'tina');
insert into nicknames values ('martine', 'tine');
insert into nicknames values ('marv', 'marvin');
insert into nicknames values ('marvin', 'marv');
insert into nicknames values ('mary', 'mae', 'mamie', 'marie', 'mitzi', 'molly', 'polly');
insert into nicknames values ('masayuki', 'masa');
insert into nicknames values ('mat', 'mattie');
insert into nicknames values ('mathew', 'mat', 'matt', 'maty');
insert into nicknames values ('mathilda', 'patty', 'tillie');
insert into nicknames values ('matilda', 'matty', 'maud', 'tilla', 'tilly');
insert into nicknames values ('matthew', 'matt', 'mattie', 'matty', 'thias', 'thys');
insert into nicknames values ('matthews', 'matt', 'mattie', 'matty');
insert into nicknames values ('matthias', 'matt', 'thias', 'thys');
insert into nicknames values ('maud', 'middy');
insert into nicknames values ('maureen', 'mary');
insert into nicknames values ('maurice', 'morey');
insert into nicknames values ('mavery', 'mave');
insert into nicknames values ('mavine', 'mave');
insert into nicknames values ('maximilian', 'max');
insert into nicknames values ('maximillian', 'max');
insert into nicknames values ('maxine', 'max');
insert into nicknames values ('maxwell', 'max');
insert into nicknames values ('may', 'mae');
insert into nicknames values ('mckenna', 'ken', 'kenna', 'meaka');
insert into nicknames values ('medora', 'dora');
insert into nicknames values ('megan', 'meg');
insert into nicknames values ('meghan', 'meg');
insert into nicknames values ('mehitabel', 'hetty', 'hitty', 'mabel', 'mitty');
insert into nicknames values ('melanie', 'mellie');
insert into nicknames values ('melchizedek', 'dick', 'zadock');
insert into nicknames values ('melinda', 'linda', 'lindy', 'lynn', 'mel', 'mindy');
insert into nicknames values ('melissa', 'lisa', 'lissa', 'mel', 'milly', 'missy');
insert into nicknames values ('mellony', 'mellia');
insert into nicknames values ('melody', 'lodi');
insert into nicknames values ('melvin', 'mel');
insert into nicknames values ('melvina', 'vina');
insert into nicknames values ('mercedes', 'merci', 'mercy', 'sadie');
insert into nicknames values ('merv', 'mervin');
insert into nicknames values ('mervin', 'merv');
insert into nicknames values ('mervyn', 'merv');
insert into nicknames values ('micajah', 'cage');
insert into nicknames values ('michael', 'micah', 'mick', 'mickey', 'micky', 'mike', 'mikey');
insert into nicknames values ('micheal', 'mike', 'mikey', 'miky');
insert into nicknames values ('michelle', 'chelle', 'mickey', 'shelley', 'shellie', 'shelly', 'shely');
insert into nicknames values ('mick', 'micky');
insert into nicknames values ('miguel', 'michael', 'miggy', 'miguael', 'miguaell', 'miguail', 'miguaill', 'miguayl', 'miguayll', 'miguell', 'mike');
insert into nicknames values ('mike', 'michael', 'mick', 'micky');
insert into nicknames values ('mildred', 'milly');
insert into nicknames values ('millicent', 'milly', 'missy');
insert into nicknames values ('minerva', 'minnie');
insert into nicknames values ('minnie', 'wilhelmina');
insert into nicknames values ('miranda', 'mandy', 'mira', 'randi', 'randy');
insert into nicknames values ('miriam', 'mimi', 'mitzi', 'mitzie');
insert into nicknames values ('missy', 'melissa');
insert into nicknames values ('mitch', 'mitchell');
insert into nicknames values ('mitchell', 'mitch');
insert into nicknames values ('mitzi', 'mary', 'mittie', 'mitty');
insert into nicknames values ('mitzie', 'mittie', 'mitty');
insert into nicknames values ('monet', 'nettie');
insert into nicknames values ('monica', 'monna', 'monnie');
insert into nicknames values ('monteleon', 'monte');
insert into nicknames values ('montesque', 'monty');
insert into nicknames values ('montgomery', 'gum', 'monty');
insert into nicknames values ('monty', 'lamont');
insert into nicknames values ('morris', 'morey');
insert into nicknames values ('mortimer', 'mort');
insert into nicknames values ('moses', 'amos', 'mose', 'moss');
insert into nicknames values ('muriel', 'mur');
insert into nicknames values ('myrtle', 'mert', 'myrt', 'myrti');
insert into nicknames values ('nadine', 'deedee', 'nada');
insert into nicknames values ('nancy', 'ann', 'nan', 'nanny');
insert into nicknames values ('naomi', 'omi');
insert into nicknames values ('napoleon', 'leon', 'nap', 'nappy');
insert into nicknames values ('natalie', 'natty', 'nettie');
insert into nicknames values ('natasha', 'nat', 'tasha');
insert into nicknames values ('nathan', 'nat', 'nate');
insert into nicknames values ('nathaniel', 'nat', 'nate', 'nathan', 'natty', 'than');
insert into nicknames values ('nelle', 'nelly');
insert into nicknames values ('nelson', 'nels');
insert into nicknames values ('newt', 'newton');
insert into nicknames values ('newton', 'newt');
insert into nicknames values ('nicholas', 'claas', 'claes', 'nic', 'nick', 'nickie', 'nicky', 'nico');
insert into nicknames values ('nicholette', 'cole', 'nichole', 'nickey', 'nicki', 'nicky', 'nicole', 'nikki');
insert into nicknames values ('nicodemus', 'nic', 'nick', 'nickie', 'nicky', 'nico');
insert into nicknames values ('nicolas', 'nic', 'nick', 'nickie', 'nicky', 'nico');
insert into nicknames values ('nicole', 'cole', 'nicki', 'nicky', 'nikki', 'nole');
insert into nicknames values ('nikolas', 'claes', 'nic', 'nick', 'nickie', 'nicky', 'nico');
insert into nicknames values ('nikole', 'nikki');
insert into nicknames values ('nora', 'nonie');
insert into nicknames values ('norbert', 'bert', 'norby');
insert into nicknames values ('norbusamte', 'norbu');
insert into nicknames values ('norman', 'norm');
insert into nicknames values ('nowell', 'noel');
insert into nicknames values ('obadiah', 'diah', 'dyer', 'obed', 'obie');
insert into nicknames values ('obediah', 'obie');
insert into nicknames values ('obedience', 'beda', 'beedy', 'biddie', 'obed');
insert into nicknames values ('obie', 'obediah');
insert into nicknames values ('octavia', 'tave', 'tavia');
insert into nicknames values ('odell', 'odo');
insert into nicknames values ('olive', 'livia', 'nollie', 'ollie');
insert into nicknames values ('oliver', 'ollie');
insert into nicknames values ('olivia', 'livia', 'nollie', 'ollie');
insert into nicknames values ('ollie', 'oliver');
insert into nicknames values ('onicyphorous', 'cy', 'cyphorus', 'one', 'osaforum', 'osaforus', 'syphorous');
insert into nicknames values ('orilla', 'ora', 'rilly');
insert into nicknames values ('orlando', 'roland');
insert into nicknames values ('orphelia', 'phelia');
insert into nicknames values ('ossy', 'ozzy');
insert into nicknames values ('oswald', 'ossy', 'ozzy', 'waldo');
insert into nicknames values ('otis', 'ode', 'ote');
insert into nicknames values ('pamela', 'pam');
insert into nicknames values ('pandora', 'dora');
insert into nicknames values ('parmelia', 'amelia', 'melia', 'milly');
insert into nicknames values ('parthenia', 'parsuny', 'pasoonie', 'phenie', 'teeny');
insert into nicknames values ('patience', 'pat', 'patty');
insert into nicknames values ('patricia', 'pat', 'patsy', 'patti', 'patty', 'tricia', 'trish', 'trisha');
insert into nicknames values ('patrick', 'paddy', 'pat', 'pate', 'patsy', 'peter');
insert into nicknames values ('patsy', 'patty');
insert into nicknames values ('patty', 'patricia');
insert into nicknames values ('paul', 'polly');
insert into nicknames values ('paula', 'lina', 'polly');
insert into nicknames values ('paulina', 'lina', 'polly');
insert into nicknames values ('pauline', 'polly');
insert into nicknames values ('peggy', 'peg');
insert into nicknames values ('pelegrine', 'perry');
insert into nicknames values ('penelope', 'penny');
insert into nicknames values ('percival', 'percy');
insert into nicknames values ('peregrine', 'perry');
insert into nicknames values ('permelia', 'mellie', 'melly', 'milly');
insert into nicknames values ('pernetta', 'nettie');
insert into nicknames values ('persephone', 'seph', 'sephy');
insert into nicknames values ('peter', 'pate', 'pete');
insert into nicknames values ('petronella', 'nellie');
insert into nicknames values ('pheney', 'josephine');
insert into nicknames values ('pheriba', 'ferbie', 'pherbia');
insert into nicknames values ('philadelphia', 'delphia');
insert into nicknames values ('philander', 'fie');
insert into nicknames values ('philetus', 'leet', 'phil');
insert into nicknames values ('philinda', 'linda', 'lindy', 'lynn');
insert into nicknames values ('philip', 'phil', 'pip');
insert into nicknames values ('philipina', 'penie', 'phoebe', 'pip');
insert into nicknames values ('phillip', 'phil', 'pip');
insert into nicknames values ('philly', 'delphia');
insert into nicknames values ('philomena', 'menaalmena');
insert into nicknames values ('phoebe', 'fifi');
insert into nicknames values ('pinckney', 'pink');
insert into nicknames values ('pleasant', 'ples');
insert into nicknames values ('pocahontas', 'pokey');
insert into nicknames values ('posthuma', 'humey');
insert into nicknames values ('prescott', 'pres', 'scott', 'scotty');
insert into nicknames values ('priscilla', 'cilla', 'cissy', 'prissy');
insert into nicknames values ('providence', 'provy');
insert into nicknames values ('prudence', 'prudy', 'prue');
insert into nicknames values ('prudy', 'prudence');
insert into nicknames values ('rachel', 'rachael', 'shelly');
insert into nicknames values ('rafaela', 'rafa');
insert into nicknames values ('ramona', 'mona');
insert into nicknames values ('randall', 'randy');
insert into nicknames values ('randolf', 'dolph', 'randy');
insert into nicknames values ('randolph', 'dolph', 'randy');
insert into nicknames values ('raphael', 'ralph');
insert into nicknames values ('ray', 'raymond');
insert into nicknames values ('raymond', 'ray');
insert into nicknames values ('reba', 'becca', 'beck');
insert into nicknames values ('rebecca', 'becca', 'beck', 'becky', 'reba');
insert into nicknames values ('reggie', 'reg', 'reginald');
insert into nicknames values ('regina', 'gina', 'reggie');
insert into nicknames values ('reginald', 'naldo', 'reg', 'reggie', 'renny');
insert into nicknames values ('relief', 'leafa');
insert into nicknames values ('reuben', 'rube');
insert into nicknames values ('reynold', 'reginald');
insert into nicknames values ('rhoda', 'rodie');
insert into nicknames values ('rhodella', 'della');
insert into nicknames values ('rhyna', 'rhynie');
insert into nicknames values ('ricardo', 'rick', 'ricky');
insert into nicknames values ('rich', 'dick', 'rick');
insert into nicknames values ('richard', 'dick', 'dickie', 'dickon', 'dicky', 'rich', 'richie', 'rick', 'ricky');
insert into nicknames values ('rick', 'ricky');
insert into nicknames values ('ricky', 'dick', 'rich');
insert into nicknames values ('robert', 'bill', 'billy', 'bob', 'bobby', 'dob', 'dobbin', 'hob', 'hobkin', 'rob', 'robby', 'rupert');
insert into nicknames values ('roberta', 'bert', 'bertie', 'birdie', 'birtie', 'bobbie', 'robbie', 'roby');
insert into nicknames values ('roberto', 'rob');
insert into nicknames values ('roderick', 'erick', 'rickie', 'rod', 'roddy');
insert into nicknames values ('rodger', 'bobby', 'hodge', 'rod', 'roge', 'roger');
insert into nicknames values ('rodney', 'rod');
insert into nicknames values ('roger', 'bobby', 'hodge', 'rod', 'rodger', 'roge');
insert into nicknames values ('roland', 'lanny', 'orlando', 'rollo', 'rolly');
insert into nicknames values ('ron', 'ronnie', 'ronny');
insert into nicknames values ('ronald', 'naldo', 'ron', 'ronnie', 'ronny');
insert into nicknames values ('ronny', 'ronald');
insert into nicknames values ('rosa', 'rose');
insert into nicknames values ('rosabel', 'belle', 'rosa', 'rose', 'roz');
insert into nicknames values ('rosabella', 'bella', 'belle', 'rosa', 'rose', 'roz');
insert into nicknames values ('rosaenn', 'ann');
insert into nicknames values ('rosaenna', 'ann');
insert into nicknames values ('rosalinda', 'linda', 'rosa', 'rose', 'roz');
insert into nicknames values ('rosalyn', 'linda', 'rosa', 'rose', 'roz');
insert into nicknames values ('roscoe', 'ross');
insert into nicknames values ('rose', 'rosie');
insert into nicknames values ('roseann', 'ann', 'rose', 'rosie', 'roz');
insert into nicknames values ('roseanna', 'ann', 'rose', 'rosie', 'roz');
insert into nicknames values ('roseanne', 'ann');
insert into nicknames values ('rosemary', 'marie', 'mary', 'rose', 'rosemarie', 'rosey');
insert into nicknames values ('rosina', 'sina');
insert into nicknames values ('roxane', 'rox', 'roxie');
insert into nicknames values ('roxanna', 'ann', 'rose', 'roxie');
insert into nicknames values ('roxanne', 'ann', 'rose', 'roxie');
insert into nicknames values ('rudolph', 'dolph', 'olph', 'rolf', 'rudy');
insert into nicknames values ('rudolphus', 'dolph', 'olph', 'rolf', 'rudy');
insert into nicknames values ('russell', 'russ', 'rusty');
insert into nicknames values ('ryan', 'ry');
insert into nicknames values ('sabrina', 'brina');
insert into nicknames values ('safieel', 'safie');
insert into nicknames values ('salome', 'loomie');
insert into nicknames values ('salvador', 'sal', 'sally');
insert into nicknames values ('sam', 'sammy');
insert into nicknames values ('samantha', 'mantha', 'sam', 'sammy');
insert into nicknames values ('sampson', 'sam', 'sammy');
insert into nicknames values ('samson', 'sam', 'sammy');
insert into nicknames values ('samuel', 'sam', 'sammy');
insert into nicknames values ('samyra', 'myra', 'sam', 'sammy');
insert into nicknames values ('sandra', 'cassandra', 'sandy');
insert into nicknames values ('sandy', 'sandra');
insert into nicknames values ('sanford', 'sandy');
insert into nicknames values ('sarah', 'sadie', 'sally', 'sara');
insert into nicknames values ('sarilla', 'silla');
insert into nicknames values ('savannah', 'anna', 'savanna', 'vannie');
insert into nicknames values ('scott', 'sceeter', 'scottie', 'scotty', 'squat');
insert into nicknames values ('sebastian', 'seb', 'sebby');
insert into nicknames values ('selma', 'anselm');
insert into nicknames values ('serena', 'rena');
insert into nicknames values ('serilla', 'rilla');
insert into nicknames values ('seymour', 'morey', 'see');
insert into nicknames values ('shaina', 'sha', 'shay');
insert into nicknames values ('sharon', 'sha', 'shay');
insert into nicknames values ('shaun', 'shawn');
insert into nicknames values ('shawn', 'shaun');
insert into nicknames values ('sheila', 'cecilia');
insert into nicknames values ('sheldon', 'shelly');
insert into nicknames values ('shelton', 'shel', 'shelly', 'tony');
insert into nicknames values ('sheridan', 'dan', 'danny', 'sher');
insert into nicknames values ('sheryl', 'cheri', 'cherie', 'sher', 'sheri', 'sherri', 'sherry', 'sherryl');
insert into nicknames values ('shirley', 'lee', 'sherry', 'shirl');
insert into nicknames values ('sibbilla', 'sibbell', 'sibbie', 'sybill');
insert into nicknames values ('sidney', 'sid', 'syd');
insert into nicknames values ('sigfired', 'sid');
insert into nicknames values ('sigfrid', 'sid');
insert into nicknames values ('sigismund', 'sig');
insert into nicknames values ('silas', 'si');
insert into nicknames values ('silence', 'liley');
insert into nicknames values ('silvester', 'si', 'sly', 'syl', 'vest', 'vester');
insert into nicknames values ('simeon', 'si', 'sion');
insert into nicknames values ('simon', 'si', 'sion');
insert into nicknames values ('smith', 'smitty');
insert into nicknames values ('socrates', 'crate');
insert into nicknames values ('solomon', 'sal', 'salmon', 'saul', 'sol', 'solly', 'zolly');
insert into nicknames values ('sondra', 'dre', 'sonnie');
insert into nicknames values ('sophia', 'sophie');
insert into nicknames values ('sophronia', 'frona', 'fronia', 'sophia');
insert into nicknames values ('stacey', 'staci', 'stacie', 'stacy');
insert into nicknames values ('stacie', 'stacey', 'staci', 'stacy');
insert into nicknames values ('stacy', 'staci');
insert into nicknames values ('stephan', 'steve');
insert into nicknames values ('stephanie', 'annie', 'steffi', 'steffie', 'steph', 'stephani', 'stephany', 'stephie', 'stephine', 'stevie');
insert into nicknames values ('stephen', 'steph', 'steve');
insert into nicknames values ('steven', 'steph', 'steve', 'stevie');
insert into nicknames values ('stuart', 'stu');
insert into nicknames values ('sue', 'susan', 'susie');
insert into nicknames values ('sullivan', 'sully', 'van');
insert into nicknames values ('susan', 'hannah', 'sue', 'sukey', 'susie', 'suzie');
insert into nicknames values ('susannah', 'hannah', 'sue', 'sukey', 'susie');
insert into nicknames values ('susie', 'suzie');
insert into nicknames values ('suzanne', 'sue', 'suki', 'susie');
insert into nicknames values ('sybill', 'sibbie');
insert into nicknames values ('sydney', 'sid');
insert into nicknames values ('sylvanus', 'sly', 'syl');
insert into nicknames values ('sylvester', 'si', 'sly', 'sy', 'syl', 'vessie', 'vester', 'vet');
insert into nicknames values ('tabby', 'tabitha');
insert into nicknames values ('tabitha', 'tabby');
insert into nicknames values ('tamarra', 'tammy');
insert into nicknames values ('tammie', 'tami', 'tammy');
insert into nicknames values ('tammy', 'tami', 'tammie');
insert into nicknames values ('tanafra', 'tanny');
insert into nicknames values ('tasha', 'tash', 'tashie');
insert into nicknames values ('ted', 'teddy');
insert into nicknames values ('temperance', 'tempy');
insert into nicknames values ('terence', 'terry');
insert into nicknames values ('teresa', 'terry', 'tess', 'tessa', 'tessie');
insert into nicknames values ('terri', 'teri', 'terrie', 'terry');
insert into nicknames values ('terry', 'terence');
insert into nicknames values ('tess', 'teresa', 'theresa');
insert into nicknames values ('tessa', 'teresa', 'theresa');
insert into nicknames values ('thad', 'thaddeus');
insert into nicknames values ('thaddeus', 'thad');
insert into nicknames values ('theo', 'theodore');
insert into nicknames values ('theodora', 'dora');
insert into nicknames values ('theodore', 'ted', 'teddy', 'theo');
insert into nicknames values ('theodosia', 'dosia', 'theo', 'theodosius');
insert into nicknames values ('theophilus', 'ophi');
insert into nicknames values ('theotha', 'otha');
insert into nicknames values ('theresa', 'terry', 'tess', 'tessa', 'tessie', 'thirza', 'thursa', 'traci', 'tracie', 'tracy');
insert into nicknames values ('thom', 'thomas', 'tom', 'tommy');
insert into nicknames values ('thomas', 'thom', 'tom', 'tommy');
insert into nicknames values ('thomasa', 'tamzine');
insert into nicknames values ('tiffany', 'tiff', 'tiffy');
insert into nicknames values ('tilford', 'tillie');
insert into nicknames values ('tim', 'timmy');
insert into nicknames values ('timothy', 'tim', 'timmy');
insert into nicknames values ('tina', 'christina');
insert into nicknames values ('tisha', 'tish');
insert into nicknames values ('tobias', 'bias', 'toby');
insert into nicknames values ('tom', 'thomas', 'tommy');
insert into nicknames values ('tony', 'anthony');
insert into nicknames values ('tranquilla', 'quilla', 'trannie');
insert into nicknames values ('trish', 'patricia', 'trisha');
insert into nicknames values ('trix', 'trixie');
insert into nicknames values ('trudy', 'gertrude');
insert into nicknames values ('tryphena', 'phena');
insert into nicknames values ('unice', 'eunice', 'nicie');
insert into nicknames values ('uriah', 'riah');
insert into nicknames values ('ursula', 'sula', 'sulie');
insert into nicknames values ('valentina', 'felty', 'val', 'vallie');
insert into nicknames values ('valentine', 'felty');
insert into nicknames values ('valeri', 'val', 'valerie');
insert into nicknames values ('valerie', 'val');
insert into nicknames values ('vanburen', 'buren');
insert into nicknames values ('vandalia', 'vannie');
insert into nicknames values ('vanessa', 'essa', 'nessa', 'vanna');
insert into nicknames values ('vernisee', 'nicey');
insert into nicknames values ('veronica', 'franky', 'frony', 'ron', 'ronie', 'ronna', 'ronnie', 'ronny', 'vonnie');
insert into nicknames values ('vic', 'vicki', 'vickie', 'vicky', 'victor');
insert into nicknames values ('vicki', 'vickie', 'vicky', 'victoria');
insert into nicknames values ('victor', 'vic');
insert into nicknames values ('victoria', 'tori', 'torie', 'torri', 'torrie', 'tory', 'vic', 'vicki', 'vickie', 'vicky');
insert into nicknames values ('vijay', 'vij');
insert into nicknames values ('vincent', 'vic', 'vin', 'vince', 'vinnie', 'vinny');
insert into nicknames values ('vincenzo', 'vic', 'vin', 'vince', 'vinnie', 'vinny');
insert into nicknames values ('vinson', 'vin', 'vince', 'vinnie', 'vinny');
insert into nicknames values ('viola', 'ola', 'vi');
insert into nicknames values ('violetta', 'lettie');
insert into nicknames values ('virginia', 'ginger', 'ginny', 'jane', 'jennie', 'virgy');
insert into nicknames values ('vivian', 'vi', 'viv');
insert into nicknames values ('waldo', 'ossy', 'ozzy');
insert into nicknames values ('wallace', 'wally');
insert into nicknames values ('wally', 'walt');
insert into nicknames values ('walter', 'wally', 'walt');
insert into nicknames values ('washington', 'wash');
insert into nicknames values ('webster', 'webb');
insert into nicknames values ('wendy', 'wen');
insert into nicknames values ('wesley', 'wes');
insert into nicknames values ('westley', 'farmboy', 'wes', 'west');
insert into nicknames values ('wilber', 'bert', 'will');
insert into nicknames values ('wilbur', 'will', 'willie', 'willy');
insert into nicknames values ('wilda', 'willie');
insert into nicknames values ('wilfred', 'fred', 'wil', 'will', 'willie');
insert into nicknames values ('wilhelm', 'wil', 'willie');
insert into nicknames values ('wilhelmina', 'mina', 'minnie', 'willie', 'wilma');
insert into nicknames values ('will', 'bill', 'fred', 'wilbur', 'willie');
insert into nicknames values ('william', 'bela', 'bell', 'bill', 'billy', 'wil', 'will', 'willie', 'willy');
insert into nicknames values ('willie', 'fred', 'william');
insert into nicknames values ('willis', 'bill', 'willy');
insert into nicknames values ('wilma', 'billiewilhelm', 'william');
insert into nicknames values ('wilson', 'will', 'willie', 'willy');
insert into nicknames values ('winfield', 'field', 'win', 'winny');
insert into nicknames values ('winifred', 'freddie', 'winnet', 'winnie');
insert into nicknames values ('winnie', 'winnifred');
insert into nicknames values ('winnifred', 'fred', 'freddie', 'freddy', 'winnie', 'winny');
insert into nicknames values ('winny', 'winnifred');
insert into nicknames values ('winton', 'wint');
insert into nicknames values ('woodrow', 'drew', 'wood', 'woody');
insert into nicknames values ('yeona', 'ona', 'onie');
insert into nicknames values ('yoshihiko', 'yoshi');
insert into nicknames values ('yulan', 'lan', 'yul');
insert into nicknames values ('yvonne', 'vonna');
insert into nicknames values ('zach', 'zack', 'zak');
insert into nicknames values ('zachariah', 'zac', 'zach', 'zachy', 'zack', 'zak', 'zakk', 'zeke');
insert into nicknames values ('zachary', 'zac', 'zach', 'zachy', 'zack', 'zak', 'zakk', 'zeke');
insert into nicknames values ('zachery', 'zac', 'zach', 'zachy', 'zack', 'zak', 'zakk', 'zeke');
insert into nicknames values ('zack', 'zach', 'zak');
insert into nicknames values ('zebedee', 'zeb');
insert into nicknames values ('zedediah', 'diah', 'dyer', 'zed');
insert into nicknames values ('zephaniah', 'zeph');
